<a href="https://colab.research.google.com/github/RamDegalasri/Pytorch-/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **TENSORS**

In [1]:
import torch
import numpy as np

# **LISTS**

In [2]:
my_list = [[1, 2, 3, 4 ,5], [6, 7, 8, 9, 10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

# **NUMPY ARRAYS**

In [3]:
np1 = np.random.rand(3, 4)

In [4]:
np1

array([[0.98717858, 0.26570433, 0.45836398, 0.06323158],
       [0.9703908 , 0.99115399, 0.506592  , 0.52665373],
       [0.83505235, 0.41083472, 0.61601944, 0.85176536]])

In [5]:
np1.dtype

dtype('float64')

# **TENSORS**

In [6]:
tensor_2d = torch.randn(3, 4)

In [7]:
tensor_2d

tensor([[ 0.0767,  1.2312, -1.2616,  0.6539],
        [-1.8226, -0.2238, -0.3790, -1.1345],
        [-0.7567,  0.4239,  0.3262,  0.2837]])

In [8]:
tensor_3d = torch.randn(2, 3, 4)

In [9]:
tensor_3d

tensor([[[-0.6000, -0.5028,  1.3314, -1.2213],
         [-0.0527,  0.6910,  0.8530,  1.9161],
         [ 0.3172, -0.8014, -1.6063,  1.6765]],

        [[-0.8423, -0.3468, -1.2949, -1.0980],
         [-1.8747,  0.2802, -1.9906, -0.3346],
         [-0.5476,  1.7568,  0.1481,  0.2001]]])

In [10]:
## Create tensor to numpy array
my_tensor = torch.tensor(np1)

In [11]:
my_tensor

tensor([[0.9872, 0.2657, 0.4584, 0.0632],
        [0.9704, 0.9912, 0.5066, 0.5267],
        [0.8351, 0.4108, 0.6160, 0.8518]], dtype=torch.float64)