<a href="https://colab.research.google.com/github/RamDegalasri/Pytorch-/blob/main/Tensor_Math_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
tensor_a = torch.tensor([1, 2, 3, 4])
tensor_b = torch.tensor([5, 6, 7, 8])

Addition

In [3]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [4]:
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

Substraction

In [8]:
4 * tensor_a - tensor_b

tensor([-1,  2,  5,  8])

In [10]:
torch.sub(tensor_a, tensor_b)

tensor([-4, -4, -4, -4])

Multiplication

In [11]:
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [12]:
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

Division

In [13]:
tensor_a / tensor_b

tensor([0.2000, 0.3333, 0.4286, 0.5000])

In [14]:
torch.div(tensor_a, tensor_b)

tensor([0.2000, 0.3333, 0.4286, 0.5000])

Remainders

In [15]:
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [16]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

Exponents

In [17]:
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])