<a href="https://colab.research.google.com/github/RamDegalasri/Pytorch-/blob/main/tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
my_torch = torch.arange(10)

In [3]:
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
my_torch = my_torch.reshape(2, 5)

In [5]:
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [6]:
my_torch2 = torch.arange(10)

In [7]:
my_torch2.view(2, 5)

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
my_torch[1][3] = 18

In [9]:
my_torch

tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7, 18,  9]])

In [12]:
#Slices
my_torch3 = torch.arange(10)

In [13]:
my_torch4 = my_torch3.reshape(5, 2)

In [14]:
my_torch4

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [15]:
my_torch4[:, 1]

tensor([1, 3, 5, 7, 9])

In [17]:
my_torch4[:, 1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])